#!/usr/bin/env node
// Auto-generated by claude-account-switch — do not edit manually
import { readFileSync, readdirSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { homedir } from 'node:os';

const PROFILES_DIR = join(homedir(), '.claude-profiles');
const META_FILE = join(PROFILES_DIR, 'meta.json');

let profiles, current;
try {
  profiles = readdirSync(PROFILES_DIR, { withFileTypes: true })
    .filter(d => d.isDirectory() && !d.name.startsWith('_'))
    .map(d => d.name);
  const meta = JSON.parse(readFileSync(META_FILE, 'utf8'));
  current = meta.activeProfile || profiles[0];
} catch {
  process.exit(1);
}

if (profiles.length === 0) process.exit(1);

if (!process.stdin.isTTY) {
  // Non-interactive fallback: output active profile
  process.stdout.write(current || profiles[0]);
  process.exit(0);
}

let selected = Math.max(0, profiles.indexOf(current));

const UP   = (n) => `\x1b[${n}A`;
const CLR  = '\x1b[2K';
const CLRD = '\x1b[0J';
const err  = process.stderr;

function hasAuth(p) {
  return existsSync(join(PROFILES_DIR, p, '.claude.json'));
}

function render(first = false) {
  if (!first) err.write(UP(profiles.length));
  for (let i = 0; i < profiles.length; i++) {
    const p        = profiles[i];
    const cursor   = i === selected ? '\x1b[36m\u276f\x1b[0m' : ' ';
    const active   = p === current  ? ' \x1b[2m(active)\x1b[0m'          : '';
    const noLogin  = !hasAuth(p)    ? ' \x1b[33m(not logged in)\x1b[0m'  : '';
    err.write(`${CLR}  ${cursor} ${p}${active}${noLogin}\n`);
  }
}

err.write('\x1b[36m[claude-account-switch]\x1b[0m Select a profile:\n');
render(true);

process.stdin.setRawMode(true);
process.stdin.resume();
process.stdin.setEncoding('utf8');

process.stdin.on('data', (key) => {
  if (key === '\x1b[A') {                    // up
    selected = (selected - 1 + profiles.length) % profiles.length;
    render();
  } else if (key === '\x1b[B') {             // down
    selected = (selected + 1) % profiles.length;
    render();
  } else if (key === '\r' || key === '\n') { // enter
    process.stdin.setRawMode(false);
    process.stdin.pause();
    err.write(`${UP(profiles.length + 1)}\r${CLR}\x1b[32m\u2713\x1b[0m Profile: \x1b[1m${profiles[selected]}\x1b[0m\n${CLRD}`);
    process.stdout.write(profiles[selected]);
    process.exit(0);
  } else if (key === '\x03') {               // ctrl-c
    process.stdin.setRawMode(false);
    process.stdin.pause();
    err.write('\n');
    process.exit(1);
  }
});
